postgres:
  host: "localhost"
  port: 5432
  dbname: "nombre_base"
  user: "usuario"
  password: "contraseña"

mysql:
  host: "localhost"
  port: 3306
  dbname: "nombre_base"
  user: "usuario"
  password: "contraseña"
